apiVersion: v1
kind: ConfigMap
metadata:
  name: strapi-config
  namespace: production
data:
  NODE_ENV: production
  DATABASE_CLIENT: postgres
  DATABASE_HOST: postgresql
  DATABASE_PORT: "5432"
  DATABASE_NAME: "strapi_db"
  DATABASE_SSL: "true"
