---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-storage-class
  namespace: kube-system
  annotations:
    "storageclass.kubernetes.io/is-default-class": "true"
provisioner: smb.csi.k8s.io
parameters:
  source: "//140.78.73.104/SAMBASHARE"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - guest
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino
