apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-volume-claim
  namespace: default
spec:
  storageClassName: smb-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
  labels:
    app: test
spec:
  containers:
    - name: test
      image: busybox
      command:
        - "sh"
        - "-c"
        - "while true; do sleep 6000; done"
      volumeMounts:
        - mountPath: /example
          name: test-volume
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: example-volume-claim
