---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http-echo-ingress-route
  namespace: web
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: web
      services:
        - name: http-echo
          namespace: web
          port: 80
  tls:
    secretName: web-cert-secret
