apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_DB
              value: "mydb"
            - name: PGDATA
              value: /var/lib/postgresql/data/db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgresql-secret.txt
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: tls
              mountPath: /etc/postgres/tls
              readOnly: true
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            - name: config
              mountPath: /etc/pgconfig
              readOnly: true
          args:
            - "-c"
            - "config_file=/etc/pgconfig/postgresql.conf"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgresql-pvc
        - name: tls
          secret:
            secretName: postgres-tls
            defaultMode: 0600
        - name: initdb
          configMap:
            name: postgresql-initdb
            defaultMode: 0600
        - name: config
          configMap:
            name: postgresql-config
            defaultMode: 0600
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch


