---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-cert
  namespace: production
spec:
  commonName: pr-busem-elastic
  secretName: elastic-cert-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - elastic
    - elastic.production.svc
    - elastic.production.svc.cluster.local
  subject:
    organizations:
      - elastic
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
