---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-cert
  namespace: production
spec:
  commonName: pr-busem-kibana
  secretName: kibana-cert-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - kibana
    - kibana.production.svc
    - kibana.production.svc.cluster.local
    - 10.42.0.0/16
  subject:
    organizations:
      - kibana
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
