apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: production
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_DB
              value: "mydb"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: tls
              mountPath: /etc/postgres/tls
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: tls
          secret:
            secretName: postgres-tls
