apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: production
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_DB
              value: "mydb"
            - name: PGDATA
              value: /var/lib/postgresql/data/db
          envFrom:
            - secretRef:
                name: postgresql-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: tls
              mountPath: /etc/postgres/tls
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgresql-pvc
        - name: tls
          secret:
            secretName: postgres-tls
