apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-filebeat-config
  namespace: kube-system
data:
  filebeat.yml: |-
    filebeat.modules:
      - module: traefik
        access:
          enabled: true
          var.paths: ["/var/log/traefik/access.log*"]
    setup.template.name: "logs-access-log-traefik"
    setup.template.pattern: "logs-access-log-traefik-*"
    output.elasticsearch:
      hosts: ["${ELASTIC_HOST}"]
      username: "${ELASTIC_USERNAME}"
      password: "${ELASTIC_PASSWORD}"
      index: "logs-access-log-traefik-%{[agent.version]}"
      ssl:
        certificate_authorities: ["/usr/share/filebeat/certs/ca.crt"]
    queue.mem:
      events: 4096
      flush.min_events: 512
