apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-filebeat-config
  namespace: kube-system
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: log
        paths:
          - /var/log/traefik/access.log
        scan_frequency: 10s
        json.keys_under_root: true
        json.add_error_key: true
        json.ignore_decoding_error: true

    output.elasticsearch:
      hosts: ["${ELASTIC_HOST}"]
      username: "${ELASTIC_USERNAME}"
      password: "${ELASTIC_PASSWORD}"
      ssl:
        verification_mode: none
