apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: longhorn-users
    namespace: web
    files:
      - .secret/htpasswd.users
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true
