apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: postgresql-secret
    namespace: production
    files:
      - postgresql-secret.txt
    type: Opaque
  - name: elastic-password
    namespace: kube-system
    files:
      - .secret/elastic-password.txt
    type: Opaque
  - name: strapi-secret
    namespace: production
    envs:
      - .secret/strapi-secret.env
    type: Opaque
  - name: mcfg-secret
    namespace: test
    envs:
      - .secret/mcfg-secret.env


generatorOptions:
  disableNameSuffixHash: true

