apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: postgresql-secret
    namespace: production
    files:
      - postgresql-secret.txt
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true

