apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

secretGenerator:
  - name: postgresql-secret
    namespace: production
    files:
      - postgresql-secret.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true
