apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: longhorn-users
    namespace: web
    files:
      - .secret/htpasswd.users
    type: Opaque
  - name: elastic-password
    namespace: kube-system
    files:
      - .secret/elastic-password.txt
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true
