---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: production
spec:
  version: 8.16.1
  count: 1
  elasticsearchRef:
    name: elastic
  config:
    server.basePath: /prod/kibana
    server.rewriteBasePath: true
  http:
    tls:
      certificate:
        secretName: kibana-cert-secret
